repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-docstring-first
      - id: detect-private-key
      - id: name-tests-test
        exclude: "fixtures.py"
      - id: requirements-txt-fixer
  - repo: https://github.com/pycqa/pylint
    rev: v2.11.1
    hooks:
      - id: pylint
        name: "Pylint"
  - repo: local
    hooks:
      - id: pytest-check
        name: Pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
