version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run
    volumes:
      - .:/usr/src/app/
    expose:
      - 5000
    env_file:
      - ./.env
    depends_on:
      - db
    container_name: flask_web
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: flask_db

volumes:
  postgres_data: