"""empty message

Revision ID: b8e9a1eba0fd
Revises: 7a8c0c53b54c
Create Date: 2021-11-10 20:44:45.265795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e9a1eba0fd'
down_revision = '7a8c0c53b54c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sites',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sites',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
